### ISSUE TITLE
Calling bottle :unneeded is deprecated

### ISSUE THREAD

**Issue by bennesp** [kwilczynski/homebrew-pkenv#3]
## Description

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the kwilczynski/pkenv tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/kwilczynski/homebrew-pkenv/Formula/pkenv.rb:8
```

Image for reference:

![Schermata 2021-11-02 alle 22 15 29](https://user-images.githubusercontent.com/5445545/139952750-4de8037d-1de0-457c-8fb7-f7edd5187a67.png)

## Context and Logs

Parameter | Value
--------- | ------------------
**macOS version:**       | 12.0.1
**Homebrew version:**   | 3.3.2-31-g7ee64d9

**Comment by kwilczynski** [comment]
Hi @bennesp,

Sorry for the delay!

Thank you for the report and sorry that this caused you some troubles! Also, thank you so much for sending a Pull Request to fix the problem. I appreciate that!

Krzysztof

**Comment by kwilczynski** [comment]
Hi @bennesp,

All merged! Thank you again! I also updated the formula so that it would install pkenv version 0.5.3 as per the upstream release, as per: https://github.com/kwilczynski/homebrew-pkenv/commit/6d88867099c6c9fb1fae46d450a40d1953854e38

Krzysztof

**Comment by bennesp** [comment]
Thank you very much Krzysztof, I really appreciate your work

**Comment by kwilczynski** [comment]
Hi @bennesp,

> Thank you very much Krzysztof, I really appreciate your work

My pleasure! There might have been a small hiccup to update the tap/formula, since I moved to main as the main repository branch name. You might have had to run `brew tap --repair`. Sorry about this!

Krzysztof
